### ISSUE TITLE
Cannot install latest due to missing Readme

### ISSUE THREAD

**Issue by jjanssen** [mikedingjan/django-svg-icons#3]
When installing django-svg-icons I get an error during installation. 

``
Collecting django-svg-icons<0.2,>=0.1
  Downloading django-svg-icons-0.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/n7/ffmw_8117v7b5635jwsx40pwmxstlj/T/pip-build-4cct2ve3/django-svg-icons/setup.py", line 19, in <module>
        long_description=open(os.path.join(PROJECT_DIR, 'README.md')).read(),
    FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/n7/ffmw_8117v7b5635jwsx40pwmxstlj/T/pip-build-4cct2ve3/django-svg-icons/README.md'
``

When downloading the `.tar.gz` from PyPi and extracting it, I can also see the `README.md` is not present in the package.

**Comment by mikedingjan** [comment]
Fixed, pushed a new version to PyPi
